services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/tymelyne
      - JWT_SECRET=your_jwt_secret_key_change_in_production
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: 