services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    container_name: tymelyne-backend
    volumes:
      - ./backend:/app
      - ./docker/start-django.sh:/start-django.sh:ro
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend,frontend,host.docker.internal
      - CORS_ORIGIN_WHITELIST=http://frontend:19000,http://frontend:19001,http://frontend:19002,http://localhost:19000,http://localhost:19001,http://localhost:19002,http://localhost:8081,http://localhost:8082,http://host.docker.internal:19000,http://host.docker.internal:19001,http://host.docker.internal:19002,exp://localhost:19000
      - CORS_ALLOW_ALL_ORIGINS=True
      - DATABASE_URL=sqlite:////app/db.sqlite3
      - STATIC_ROOT=/app/staticfiles
    networks:
      - tymelyne-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:8000/api/ | grep -q 401"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    command: ["/bin/bash", "/start-django.sh"]

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    container_name: tymelyne-frontend
    volumes:
      - ./frontend:/app
      - ./docker/start-expo.sh:/start-expo.sh
      - node_modules:/app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
      - "8082:8082"
    environment:
      - EXPO_PACKAGER_HOSTNAME=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - REACT_APP_API_URL=docker
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_WEB_INFO=true
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - WATCHPACK_POLLING=true
    depends_on:
      backend:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - tymelyne-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: ["/start-expo.sh"]

networks:
  tymelyne-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16

volumes:
  node_modules: 