services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    container_name: tymelyne-backend
    volumes:
      - ./backend:/app
      - ./docker/start-django.sh:/start-django.sh
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - CORS_ORIGIN_WHITELIST=http://frontend:19000,http://localhost:19000,http://localhost:19001,http://localhost:19002
    networks:
      - tymelyne-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/ || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: ["/start-django.sh"]

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    container_name: tymelyne-frontend
    volumes:
      - ./frontend:/app
      - ./docker/start-expo.sh:/start-expo.sh
      - node_modules:/app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
      - "8082:8082"
    environment:
      - EXPO_PACKAGER_HOSTNAME=0.0.0.0
      - REACT_APP_API_URL=docker
    depends_on:
      - backend
    networks:
      - tymelyne-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: ["/start-expo.sh"]

networks:
  tymelyne-network:
    driver: bridge

volumes:
  node_modules: 