# Generated by Django 5.0.2 on 2025-03-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                help_text="User avatar URL from Supabase",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, help_text="User full name", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="User profile picture (local storage)",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
